EventId,EventTemplate,Occurrences
624adc5d,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- <*> o.s.s.p.customers.web.OwnerResource : List all owners in the pet clinic,1938
e6da5d48,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- <*> <*> : <*> <*> owner - <*> User<*>,1442
05aadbca,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- <*> <*> : Find <*> <*> <*> id - <*>,4387
009b64e6,"<*> - - [<*>/Jun/<*>:<*>:<*>:<*> <*>] ""GET /metrics HTTP/<*>.<*>"" <*> <*> ""-"" ""Prometheus/"" <*> <*>.<*> [] [] - - - - <*>",219
622430e8,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- <*> o.s.s.p.customers.web.PetResource : Request received to add a pet to owner : <*>,1308
fee75247,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- <*> o.s.s.p.customers.web.PetResource : Find owner for id - <*>,1312
5b7a1128,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- <*> o.s.s.p.customers.web.PetResource : Successfully added pet : null to owner : Test<*>,1312
ccbb2484,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- <*> o.s.s.p.customers.web.PetResource : Pet name set to: <*>,1306
620a867a,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- <*> o.s.s.p.customers.web.PetResource : Pet birthdate set to: <*> <*> <*> <*>:<*>:<*> UTC <*>,1319
84a7cbcc,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- <*> o.s.s.p.customers.web.PetResource : Saving pet <*> id = [null], name = <*> birthDate = <*> <*> <*> <*>:<*>:<*> UTC <*>, type = 'dog', ownerFirstname = <*> ownerLastname = <*>",1336
4ace852c,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- <*> o.s.s.p.visits.web.VisitResource : Get visit information for pet - <*>,472
7ddd0e2c,"2021-<*>-<*> <*>:<*>:<*>.<*> WARN <*> <*> --- <*> o.h.engine.jdbc.spi.SqlExceptionHelper : SQL Error: <*>, SQLState: <*>",74
19fcf69a,2021-<*>-<*> <*>:<*>:<*>.<*> ERROR <*> <*> --- <*> o.h.engine.jdbc.spi.SqlExceptionHelper : Table <*> doesn't exist,44
02d30163,<*> <*>:<*>:<*>.<*> <*> proxier.go:<*>] Syncing iptables rules,277
266af2f8,2021-<*>-<*> <*>:<*>:<*> <*> [Note] mysqld: <*> <*>,58
fbe9fb2a,2021-<*>-<*> <*>:<*>:<*> <*> [Note] Giving <*> client threads a chance to die gracefully,33
10795bcf,2021-<*>-<*> <*>:<*>:<*> <*> [Note] Event Scheduler: Purging the queue. <*> events,33
f233d567,2021-<*>-<*> <*>:<*>:<*> <*> [Note] Shutting down <*> <*>,1316
56760379,<*> <*>:<*>:<*>.<*> <*> proxier.go:<*>] syncProxyRules took <*>,275
8d8096b1,2021-<*>-<*> <*>:<*>:<*> <*> [Note] Forcefully disconnecting <*> remaining clients,33
96b475ab,2021-<*>-<*> <*>:<*>:<*> <*> [Warning] mysqld: Forcing close of thread <*> user: 'root',130
da1e4217,2021-<*>-<*> <*>:<*>:<*> <*> [Note] Binlog end,73
2dd70cfe,2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: FTS optimize thread exiting.,73
dd8b324d,2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: Starting shutdown...,73
5dd1aeba,2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: <*> <*> log sequence number <*>,146
7181c54c,2021-<*>-<*> <*>:<*>:<*>.<*> WARN <*> <*> --- <*> com.zaxxer.hikari.pool.PoolBase : HikariPool-<*> - Failed to validate connection <*> (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.,224
8358b719,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- <*> o.s.s.p.visits.web.VisitResource : Set pet id to - <*> for visit,478
1ee14fcd,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- [nio-<*>-exec-<*>] <*> : <*> <*> <*>,56
4efe9eaa,"2021-<*>-<*> <*>:<*>:<*>.<*> ERROR <*> <*> --- <*> o.h.engine.jdbc.spi.SqlExceptionHelper : HikariPool-<*> - Connection is not available, request timed out after <*>",30
23e2bd8d,2021-<*>-<*> <*>:<*>:<*>.<*> ERROR <*> <*> --- <*> o.h.engine.jdbc.spi.SqlExceptionHelper : Communications link failure The last packet sent successfully to the server was <*> milliseconds ago. The driver has not received any packets from the server.,26
efd87f88,"2021-<*>-<*> <*>:<*>:<*>.<*> ERROR [visits-service,,,] <*> --- [nio-<*>-exec-<*>] o.a.c.c.C.[.[.[/].[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: Unable to acquire JDBC Connection; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection] with root cause java.net.UnknownHostException: visits-db-mysql.spring-petclinic.svc.cluster.local: Name or service not known at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) at java.net.InetAddress$<*>.lookupAllHostAddr(InetAddress.java:<*>) at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:<*>) at java.net.InetAddress.getAllByName0(InetAddress.java:<*>) at java.net.InetAddress.getAllByName(InetAddress.java:<*>) at java.net.InetAddress.getAllByName(InetAddress.java:<*>) at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:<*>) at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:<*>) at com.mysql.cj.NativeSession.connect(NativeSession.java:<*>) at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:<*>) at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:<*>) at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:<*>) at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:<*>) at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:<*>) at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:<*>) at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:<*>) at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:<*>) at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:<*>) at com.zaxxer.hikari.pool.HikariPool.access$<*>(HikariPool.java:<*>) at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:<*>) at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:<*>) at java.util.concurrent.FutureTask.run(FutureTask.java:<*>) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:<*>) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:<*>) at java.lang.Thread.run(Thread.java:<*>)",10
425bd914,2021-<*>-<*> <*>:<*>:<*>.<*> ERROR <*> <*> --- <*> o.a.c.c.C.[.[.[/].[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection] with root cause java.net.UnknownHostException: <*> Name or service not known at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) at java.net.InetAddress$<*>.lookupAllHostAddr(InetAddress.java:<*>) at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:<*>) at java.net.InetAddress.getAllByName0(InetAddress.java:<*>) at java.net.InetAddress.getAllByName(InetAddress.java:<*>) at java.net.InetAddress.getAllByName(InetAddress.java:<*>) at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:<*>) at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:<*>) at com.mysql.cj.NativeSession.connect(NativeSession.java:<*>) at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:<*>) at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:<*>) at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:<*>) at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:<*>) at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:<*>) at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:<*>) at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:<*>) at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:<*>) at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:<*>) at com.zaxxer.hikari.pool.HikariPool.access$<*>(HikariPool.java:<*>) at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:<*>) at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:<*>) at java.util.concurrent.FutureTask.run(FutureTask.java:<*>) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:<*>) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:<*>) at java.lang.Thread.run(Thread.java:<*>),13
6891ccfd,"2021-<*>-<*> <*>:<*>:<*>.<*> ERROR [visits-service,,,] <*> --- [nio-<*>-exec-<*>] o.a.c.c.C.[.[.[/].[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: Unable to acquire JDBC Connection; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection] with root cause java.net.UnknownHostException: visits-db-mysql.spring-petclinic.svc.cluster.local at java.net.InetAddress.getAllByName0(InetAddress.java:<*>) at java.net.InetAddress.getAllByName(InetAddress.java:<*>) at java.net.InetAddress.getAllByName(InetAddress.java:<*>) at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:<*>) at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:<*>) at com.mysql.cj.NativeSession.connect(NativeSession.java:<*>) at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:<*>) at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:<*>) at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:<*>) at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:<*>) at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:<*>) at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:<*>) at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:<*>) at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:<*>) at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:<*>) at com.zaxxer.hikari.pool.HikariPool.access$<*>(HikariPool.java:<*>) at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:<*>) at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:<*>) at java.util.concurrent.FutureTask.run(FutureTask.java:<*>) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:<*>) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:<*>) at java.lang.Thread.run(Thread.java:<*>)",1
855d89d9,"2021-<*>-<*> <*>:<*>:<*>.<*> ERROR [visits-service,,,] <*> --- [nio-<*>-exec-<*>] o.a.c.c.C.[.[.[/].[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection] with root cause java.net.UnknownHostException: visits-db-mysql.spring-petclinic.svc.cluster.local at java.net.InetAddress.getAllByName0(InetAddress.java:<*>) at java.net.InetAddress.getAllByName(InetAddress.java:<*>) at java.net.InetAddress.getAllByName(InetAddress.java:<*>) at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:<*>) at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:<*>) at com.mysql.cj.NativeSession.connect(NativeSession.java:<*>) at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:<*>) at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:<*>) at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:<*>) at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:<*>) at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:<*>) at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:<*>) at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:<*>) at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:<*>) at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:<*>) at com.zaxxer.hikari.pool.HikariPool.access$<*>(HikariPool.java:<*>) at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:<*>) at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:<*>) at java.util.concurrent.FutureTask.run(FutureTask.java:<*>) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:<*>) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:<*>) at java.lang.Thread.run(Thread.java:<*>)",1
9846de00,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- [nio-<*>-exec-<*>] o.a.c.c.C.[Tomcat].[localhost].[/] : Initializing Spring DispatcherServlet 'dispatcherServlet',34
a1ecff1c,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- [nio-<*>-exec-<*>] o.s.web.servlet.DispatcherServlet : Completed initialization in <*> ms,34
49cbaacd,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- <*> o.s.s.p.visits.web.VisitResource : Saving visit <*>,440
c6ac76fa,<*> <*>:<*>:<*>.<*> <*> service.go:<*>] Service <*> updated: <*> ports,42
6ca2f06c,<*> <*>:<*>:<*>.<*> <*> service.go:<*>] Adding new service port <*> at <*>/TCP,84
142f0b3d,"<*> <*>:<*>:<*>.<*> <*> proxier.go:<*>] Opened local port ""nodePort for chaos-testing/chaos-dashboard:http"" (:<*>/tcp)",22
08d0a6d4,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- [tomcat-shutdown] o.s.b.w.e.tomcat.GracefulShutdown : Graceful shutdown complete,6
e387fce4,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- [extShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default',6
fd720773,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO [customers-service,,,] <*> --- [extShutdownHook] <*> : <*> <*> <*> <*>",3
19aa1f1b,2021-<*>-<*> <*>:<*>:<*>.<*> ERROR <*> <*> --- <*> a.w.r.e.AbstractErrorWebExceptionHandler : <*> <*> Server Error for HTTP <*> <*> io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: <*> Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: Error has been observed at the following site(s): |_ checkpoint ? org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain] |_ checkpoint ? org.springframework.cloud.sleuth.instrument.web.TraceWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain] |_ checkpoint ? HTTP <*> <*> [ExceptionHandlingWebHandler] Stack trace: Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused at io.netty.channel.unix.Errors.throwConnectException(Errors.java:<*>) at io.netty.channel.unix.Socket.finishConnect(Socket.java:<*>) at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:<*>) at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:<*>) at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:<*>) at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:<*>) at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:<*>) at io.netty.util.concurrent.SingleThreadEventExecutor$<*>.run(SingleThreadEventExecutor.java:<*>) at io.netty.util.internal.ThreadExecutorMap$<*>.run(ThreadExecutorMap.java:<*>) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:<*>) at java.lang.Thread.run(Thread.java:<*>),9
c216ff37,Setting Active Processor Count to <*>,7
0ac02e4a,Adding <*> container CA certificates to JVM truststore,7
fcebb0d6,Spring Cloud Bindings Enabled,7
d41d8cd9,,14
a80891c7,. ____ _ __ _ _,7
9900f765,/\\ / ___'_ __ _ _(_)_ __ __ _ \ \ \ \,7
f82bb76a,\\/ ___)| |_)| | | | | || (_| | ) ) ) ),7
d3ba16af,=========|_|==============|___/=/_/_/_/,7
cbf17d99,:: Spring Boot :: (v2.<*>.<*>.RELEASE),7
93bdaf41,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO [customers-service,,,] <*> --- [ main] <*> : <*> <*> <*> <*> <*>",4
13833814,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO [customers-service,,,] <*> --- [ main] <*> : <*> <*> <*> <*> <*> <*>",4
e0efd749,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- [ main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFERRED mode.,6
df235259,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- [ main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in <*> Found <*> JPA repository interfaces.,6
cc8a23d1,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- [ main] o.s.cloud.context.scope.GenericScope : BeanFactory <*>,7
ced7bc75,"2021-<*>-<*> <*>:<*>:<*>.<*> <*> [customers-service,,,] <*> --- [ main] <*> : <*> <*> <*>",4
f5a2d79c,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO [customers-service,,,] <*> --- [ <*> <*> : <*> <*> <*> <*>",5
6ef7c1c5,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO [customers-service,,,] <*> --- [ main] <*> : <*> <*> initialization <*> <*> <*> <*>",2
9859baef,"2021-<*>-<*> <*>:<*>:<*>.<*> WARN <*> <*> --- [ main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning",6
44e603d0,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- [ task-<*>] org.hibernate.Version : HHH000412: Hibernate ORM core version <*>.<*>.<*>.Final,6
1e0c7ed1,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO [customers-service,,,] <*> --- [ task-<*>] <*> : <*> <*> <*> <*> <*>",2
2de5db63,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- [ main] o.s.s.web.DefaultSecurityFilterChain : Creating filter chain: any request, <*> <*> <*> <*> <*> <*> <*> <*> <*> <*>",6
fc386368,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- [ main] o.s.b.a.e.web.EndpointLinksResolver : Exposing <*> endpoint(s) beneath base path '/actuator',7
09bdf515,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- [ main] <*> : Started <*> in <*>.<*> seconds (JVM running for <*>.<*>),6
b4040e25,"2021-<*>-<*> <*>:<*>:<*>.<*> WARN <*> <*> --- <*> .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [<*>] in public org.springframework.samples.petclinic.customers.model.Owner org.springframework.samples.petclinic.customers.web.OwnerResource.createOwner(org.springframework.samples.petclinic.customers.model.Owner): [Field error in object 'owner' on field 'telephone': rejected value [<*>]; codes [Digits.owner.telephone,Digits.telephone,Digits.java.lang.String,Digits]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [owner.telephone,telephone]; arguments []; default message [telephone],<*>,<*>]; default message [numeric value out of bounds (<<*> digits>.<<*> digits> expected)]] ]",181
7eccbb1a,"<*> - - [<*>/Jun/<*>:<*>:<*>:<*> <*>] ""POST /tot43/DESKTOP-JGLLJLF_W10016299.1CF3DD28B304BBF734B33FBDF1762BBE/<*>/ HTTP/<*>.<*>"" <*> <*> ""-"" ""Mozilla/<*>.<*> (Windows NT <*>.<*>; Win64; x64; rv:<*>.<*>) Gecko/<*> Firefox/<*>.<*>"" <*> <*>.<*> [] [] - - - - 0cb9e483c3c75bf4fdb422d5397a5be<*>",1
4f38793c,2021-<*>-<*> <*>:<*>:<*>+<*>:<*> [Note] [Entrypoint]: Entrypoint script for MySQL Server <*>.<*>.<*>-1debian9 started.,40
1cb844e0,2021-<*>-<*> <*>:<*>:<*>+<*>:<*> [Note] [Entrypoint]: Switching to dedicated user 'mysql',20
5edbc687,"2021-<*>-<*> <*>:<*>:<*>+<*>:<*> [Note] [Entrypoint]: Initializing database files PLEASE REMEMBER TO SET A PASSWORD FOR THE MySQL root USER ! To do so, start the server, then issue the following commands: /usr/bin/mysqladmin -u root password 'new-password' /usr/bin/mysqladmin -u root -h <*> password 'new-password' Alternatively you can run: /usr/bin/mysql_secure_installation which will also give you the option of removing the test databases and anonymous user created by default. This is strongly recommended for production servers. See the manual for more instructions. Please report any problems at http://bugs.mysql.com/ The latest information about MySQL is available on the web at http://www.mysql.com Support MySQL by buying support/licenses at http://shop.mysql.com Note: new default config file not created. Please make sure your config file is current WARNING: Default config file /etc/mysql/my.cnf exists on the system This file will be read by default by the MySQL server If you do not want to use this, either remove it, or use the --defaults-file argument to mysqld_safe when starting the server",20
0ea2cd0a,2021-<*>-<*> <*>:<*>:<*> <*> [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).,80
a83942b0,2021-<*>-<*> <*>:<*>:<*> <*> [Note] Ignoring --secure-file-priv value as server is running with --bootstrap.,40
64226c7d,2021-<*>-<*> <*>:<*>:<*> <*> [Note] <*> (mysqld <*>.<*>.<*>) starting as process <*> ...,80
b2bb8d29,2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: Using atomics to ref count buffer pool pages,80
1813dccf,2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: The InnoDB memory heap is disabled,80
0fd215b6,2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins,80
f5e78513,2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: Memory barrier is not used,80
10d6c1fb,2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: Compressed tables use zlib <*>.<*>.<*>,80
e96c322e,2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: Using <*> <*> <*>,160
89757640,"2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: Initializing buffer pool, size = <*>.0M",80
46b2b57a,2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: Completed initialization of buffer pool,80
98ac50a2,2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: The first specified data file ./ibdata1 did not exist: a new database to be created!,20
5cddc9f2,2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: Setting file ./ibdata1 size to <*> MB,20
f8cbfaa5,2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: Database physically writes the file full: wait...,20
90e2a27d,2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: Setting log file <*> size to <*> MB,40
7ba6175c,2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: Renaming log file ./ib_logfile101 to ./ib_logfile<*>,20
f787c356,"2021-<*>-<*> <*>:<*>:<*> <*> [Warning] InnoDB: New log files created, LSN=<*>",20
40e60a84,2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: Doublewrite buffer not found: creating new,20
a9f8140d,2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: Doublewrite buffer created,20
8aaf3823,2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: <*> rollback segment(s) are active.,80
9f3524b5,2021-<*>-<*> <*>:<*>:<*> <*> <*> InnoDB: Creating <*> <*> <*> system tables.,40
df6ebb57,2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: <*> <*> <*> system tables <*>,40
6ea5bce4,2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: Waiting for purge to start,80
2f516fbe,2021-<*>-<*> <*>:<*>:<*> <*> [Note] RSA <*> key file not found: <*> Some authentication plugins will not work.,160
643eb281,2021-<*>-<*> <*>:<*>:<*> <*> [Note] InnoDB: Highest supported file format is Barracuda.,60
c703e7e7,2021-<*>-<*> <*>:<*>:<*>+<*>:<*> [Note] [Entrypoint]: <*> <*> <*>,140
cd31948d,2021-<*>-<*> <*>:<*>:<*>+<*>:<*> [Note] [Entrypoint]: Waiting for server startup,20
ec7aee9e,2021-<*>-<*> <*>:<*>:<*> <*> [Note] Plugin 'FEDERATED' is disabled.,40
7d1ea0dd,"2021-<*>-<*> <*>:<*>:<*> <*> [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: <*>",20
3b9af9a3,2021-<*>-<*> <*>:<*>:<*> <*> [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.,40
d038e45a,2021-<*>-<*> <*>:<*>:<*> <*> [Warning] 'user' entry <*> ignored in --skip-name-resolve mode.,40
85f8dd50,2021-<*>-<*> <*>:<*>:<*> <*> [Warning] 'proxies_priv' entry '@ <*> ignored in --skip-name-resolve mode.,59
5f4544dc,2021-<*>-<*> <*>:<*>:<*> <*> [Note] Event Scheduler: Loaded <*> events,39
5aba2f40,2021-<*>-<*> <*>:<*>:<*> <*> [Note] mysqld: ready for connections. Version: '<*>.<*>.<*>' socket: '/var/run/mysqld/mysqld.sock' port: <*> MySQL Community Server (GPL) Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it. Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it. Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it. Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.,20
e5c826fe,2021-<*>-<*> <*>:<*>:<*>+<*>:<*> [Note] [Entrypoint]: Giving user petclinic access to schema service_instance_db,20
d3e57276,2021-<*>-<*> <*>:<*>:<*>+<*>:<*> [Note] [Entrypoint]: MySQL init process done. Ready for start up.,19
a03be0be,2021-<*>-<*> <*>:<*>:<*> <*> [Note] Server hostname (bind-address): '*'; port: <*>,20
1d9cf645,2021-<*>-<*> <*>:<*>:<*> <*> [Note] IPv6 is available.,20
14a285b7,2021-<*>-<*> <*>:<*>:<*> <*> [Note] - '::' resolves to '::';,20
d6b3d3fd,2021-<*>-<*> <*>:<*>:<*> <*> [Note] Server socket created on IP: '::'.,20
3d565523,2021-<*>-<*> <*>:<*>:<*> <*> [Note] mysqld: ready for connections. Version: '<*>.<*>.<*>' socket: '/var/run/mysqld/mysqld.sock' port: <*> MySQL Community Server (GPL),19
6d2a1726,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- [extShutdownHook] <*> : Commencing graceful shutdown. Waiting for active requests to complete,6
536f158e,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO [vets-service,,,] <*> --- [extShutdownHook] <*> : <*> <*> <*> <*>",9
57a06f46,Calculating JVM memory based on <*> available memory,6
c806034b,"Calculated JVM Memory Configuration: -XX:MaxDirectMemorySize=10M <*> <*> -XX:ReservedCodeCacheSize=240M -Xss1M (Total Memory: <*> Thread Count: <*>, Loaded Class Count: <*>, Headroom: <*>%)",6
802d1ed3,Picked up JAVA_TOOL_OPTIONS: -Djava.security.properties=/layers/paketo-buildpacks_bellsoft-liberica/java-security-properties/java-security.properties -agentpath:/layers/paketo-buildpacks_bellsoft-liberica/jvmkill/jvmkill-<*>.<*>.<*>-RELEASE.so=printHeapHistogram=<*> -XX:ActiveProcessorCount=<*> -XX:MaxDirectMemorySize=10M <*> <*> -XX:ReservedCodeCacheSize=240M -Xss1M -Dorg.springframework.cloud.bindings.boot.enable=true,6
9651d49d,( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \,6
aba10c67,"' |____| .__|_| |_|_| |_\__, | / / / /",6
ea5007bf,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO [vets-service,,,] <*> --- [ main] <*> : <*> <*> <*> <*> <*>",12
7cc58577,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO [vets-service,,,] <*> --- [ main] <*> : <*> <*> <*> <*> <*> <*>",12
92a06c47,"2021-<*>-<*> <*>:<*>:<*>.<*> <*> [vets-service,,,] <*> --- [ main] <*> : <*> <*> <*>",15
fc630247,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO [vets-service,,,] <*> --- [ <*> <*> : <*> <*> <*> <*>",15
95315721,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO [vets-service,,,] <*> --- [ main] <*> : <*> <*> initialization <*> <*> <*> <*>",6
349d3181,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO [vets-service,,,] <*> --- [ task-<*>] <*> : <*> <*> <*> <*> <*>",9
f70657f6,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- [ task-<*>] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default',5
9bacb2cb,2021-<*>-<*> <*>:<*>:<*>.<*> INFO <*> <*> --- [ main] o.s.b.w.embedded.tomcat.TomcatWebServer : Tomcat started on port(s): <*> (http) with context path '',5
bc8df2d1,"<*> - - [<*>/Jun/<*>:<*>:<*>:<*> <*>] ""GET / HTTP/<*>.<*>"" <*> <*> ""-"" ""Mozilla/<*>.<*> (Linux; Android <*>.<*>.<*>; Lenovo P1a42) AppleWebKit/<*>.<*> (KHTML, like Gecko) Chrome<*> Mobile Safari/<*>.<*>"" <*> <*>.<*> [] [] - - - - ba878351f4f612a2ad8a8991d84a703d",1
6a620591,2021-<*>-<*> <*>:<*>:<*>.<*> ERROR <*> <*> --- <*> o.h.engine.jdbc.spi.SqlExceptionHelper : No operations allowed after connection closed.,4
3a3a42f4,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO [visits-service,,,] <*> --- [extShutdownHook] <*> : <*> <*> <*> <*>",6
66d7900e,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO [visits-service,,,] <*> --- [ main] <*> : <*> <*> <*> <*> <*>",8
fccf38d8,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO [visits-service,,,] <*> --- [ main] <*> : <*> <*> <*> <*> <*> <*>",8
5fcffbc1,"2021-<*>-<*> <*>:<*>:<*>.<*> <*> [visits-service,,,] <*> --- [ main] <*> : <*> <*> <*>",10
c65481b0,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO [visits-service,,,] <*> --- [ <*> <*> : <*> <*> <*> <*>",10
347d5320,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO [visits-service,,,] <*> --- [ main] <*> : <*> <*> initialization <*> <*> <*> <*>",4
1d56db3f,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO [visits-service,,,] <*> --- [ task-<*>] <*> : <*> <*> <*> <*> <*>",6
134e6e86,20:<*>:<*>.<*> [main] INFO org.springframework.samples.petclinic.api.ApiGatewayApplication - Running API gateway with args - {},1
8b6134fb,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO [api-gateway,,,] <*> --- [ main] <*> : <*> <*> <*> <*> <*>",6
0d66ddc4,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO [api-gateway,,,] <*> --- [ main] <*> : <*> <*> <*> <*> <*> <*>",2
fa4216ec,"2021-<*>-<*> <*>:<*>:<*>.<*> WARN [api-gateway,,,] <*> --- [ main] o.s.boot.actuate.endpoint.EndpointId : Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.",1
a9f7263d,"2021-<*>-<*> <*>:<*>:<*>.<*> INFO [api-gateway,,,] <*> --- [ <*> <*> : <*> <*> <*>",14
b5b11e72,2021-<*>-<*> <*>:<*>:<*>.<*> WARN <*> <*> --- [<*>/...] i.f.k.c.d.i.WatchConnectionManager : Exec Failure javax.net.ssl.SSLException: Connection timed out (Read failed) at sun.security.ssl.Alert.createSSLException(Alert.java:<*>) at sun.security.ssl.TransportContext.fatal(TransportContext.java:<*>) at sun.security.ssl.TransportContext.fatal(TransportContext.java:<*>) at sun.security.ssl.TransportContext.fatal(TransportContext.java:<*>) at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:<*>) at sun.security.ssl.SSLSocketImpl.access$<*>(SSLSocketImpl.java:<*>) at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:<*>) at okio.Okio$<*>.read(Okio.java:<*>) at okio.AsyncTimeout$<*>.read(AsyncTimeout.java:<*>) at okio.RealBufferedSource.request(RealBufferedSource.java:<*>) at okio.RealBufferedSource.require(RealBufferedSource.java:<*>) at okio.RealBufferedSource.readByte(RealBufferedSource.java:<*>) at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:<*>) at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:<*>) at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:<*>) at okhttp3.internal.ws.RealWebSocket$<*>.onResponse(RealWebSocket.java:<*>) at okhttp3.RealCall$AsyncCall.execute(RealCall.java:<*>) at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:<*>) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:<*>) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:<*>) at java.lang.Thread.run(Thread.java:<*>) Suppressed: java.net.SocketException: Broken pipe (Write failed) at java.net.SocketOutputStream.socketWrite0(Native Method) at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:<*>) at java.net.SocketOutputStream.write(SocketOutputStream.java:<*>) at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:<*>) at sun.security.ssl.TransportContext.fatal(TransportContext.java:<*>) ... <*> common frames omitted Caused by: java.net.SocketException: Connection timed out (Read failed) at java.net.SocketInputStream.socketRead0(Native Method) at java.net.SocketInputStream.socketRead(SocketInputStream.java:<*>) at java.net.SocketInputStream.read(SocketInputStream.java:<*>) at java.net.SocketInputStream.read(SocketInputStream.java:<*>) at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:<*>) at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:<*>) at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:<*>) at sun.security.ssl.SSLSocketImpl.access$<*>(SSLSocketImpl.java:<*>) at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:<*>) ... <*> common frames omitted,2
19d00445,"2021-<*>-<*> <*>:<*>:<*>.<*> WARN [vets-service,,,] <*> --- [<*>/...] i.f.k.c.d.i.WatchConnectionManager : Exec Failure javax.net.ssl.SSLException: Read timed out at sun.security.ssl.Alert.createSSLException(Alert.java:<*>) at sun.security.ssl.TransportContext.fatal(TransportContext.java:<*>) at sun.security.ssl.TransportContext.fatal(TransportContext.java:<*>) at sun.security.ssl.TransportContext.fatal(TransportContext.java:<*>) at sun.security.ssl.SSLTransport.decode(SSLTransport.java:<*>) at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:<*>) at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:<*>) at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:<*>) at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:<*>) at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:<*>) at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:<*>) at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:<*>) at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:<*>) at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:<*>) at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:<*>) at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createHttpClient$<*>(HttpClientUtils.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:<*>) at okhttp3.RealCall$AsyncCall.execute(RealCall.java:<*>) at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:<*>) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:<*>) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:<*>) at java.lang.Thread.run(Thread.java:<*>) Caused by: java.net.SocketTimeoutException: Read timed out at java.net.SocketInputStream.socketRead0(Native Method) at java.net.SocketInputStream.socketRead(SocketInputStream.java:<*>) at java.net.SocketInputStream.read(SocketInputStream.java:<*>) at java.net.SocketInputStream.read(SocketInputStream.java:<*>) at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:<*>) at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:<*>) at sun.security.ssl.SSLTransport.decode(SSLTransport.java:<*>) ... <*> common frames omitted",4
e65f4130,"2021-<*>-<*> <*>:<*>:<*>.<*> ERROR [api-gateway,ceb4a4f8b9b47893,ceb4a4f8b9b47893,true] <*> --- [pool-<*>-thread-<*>] o.s.c.k.d.KubernetesCatalogWatch : Error watching Kubernetes Services io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list] for kind: [Endpoints] with name: [null] in namespace: [spring-petclinic] failed. at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:<*>) at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:<*>) at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:<*>) at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:<*>) at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:<*>) at org.springframework.cloud.kubernetes.discovery.KubernetesCatalogWatch.catalogServicesWatch(KubernetesCatalogWatch.java:<*>) at org.springframework.cloud.kubernetes.discovery.KubernetesCatalogWatch$$FastClassBySpringCGLIB$$b5625982.invoke(<generated>) at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:<*>) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:<*>) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:<*>) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:<*>) at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:<*>) at org.springframework.cloud.sleuth.instrument.scheduling.TraceSchedulingAspect.traceBackgroundThread(TraceSchedulingAspect.java:<*>) at sun.reflect.GeneratedMethodAccessor112.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:<*>) at java.lang.reflect.Method.invoke(Method.java:<*>) at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:<*>) at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:<*>) at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:<*>) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:<*>) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:<*>) at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:<*>) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:<*>) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:<*>) at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:<*>) at org.springframework.cloud.kubernetes.discovery.KubernetesCatalogWatch$$EnhancerBySpringCGLIB$$<*>.catalogServicesWatch(<generated>) at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:<*>) at java.lang.reflect.Method.invoke(Method.java:<*>) at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:<*>) at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:<*>) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:<*>) at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:<*>) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$<*>(ScheduledThreadPoolExecutor.java:<*>) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:<*>) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:<*>) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:<*>) at java.lang.Thread.run(Thread.java:<*>) Caused by: javax.net.ssl.SSLException: Connection timed out (Read failed) at sun.security.ssl.Alert.createSSLException(Alert.java:<*>) at sun.security.ssl.TransportContext.fatal(TransportContext.java:<*>) at sun.security.ssl.TransportContext.fatal(TransportContext.java:<*>) at sun.security.ssl.TransportContext.fatal(TransportContext.java:<*>) at sun.security.ssl.SSLTransport.decode(SSLTransport.java:<*>) at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:<*>) at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:<*>) at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:<*>) at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:<*>) at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:<*>) at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:<*>) at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:<*>) at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:<*>) at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:<*>) at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:<*>) at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createHttpClient$<*>(HttpClientUtils.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:<*>) at okhttp3.RealCall.execute(RealCall.java:<*>) at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:<*>) at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:<*>) at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:<*>) at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:<*>) ... <*> common frames omitted Suppressed: java.net.SocketException: Broken pipe (Write failed) at java.net.SocketOutputStream.socketWrite0(Native Method) at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:<*>) at java.net.SocketOutputStream.write(SocketOutputStream.java:<*>) at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:<*>) at sun.security.ssl.TransportContext.fatal(TransportContext.java:<*>) ... <*> common frames omitted Caused by: java.net.SocketException: Connection timed out (Read failed) at java.net.SocketInputStream.socketRead0(Native Method) at java.net.SocketInputStream.socketRead(SocketInputStream.java:<*>) at java.net.SocketInputStream.read(SocketInputStream.java:<*>) at java.net.SocketInputStream.read(SocketInputStream.java:<*>) at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:<*>) at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:<*>) at sun.security.ssl.SSLTransport.decode(SSLTransport.java:<*>) ... <*> common frames omitted",1
ca42c6cc,"2021-<*>-<*> <*>:<*>:<*>.<*> WARN [api-gateway,,,] <*> --- [or-http-epoll-<*>] r.netty.http.client.HttpClientConnect : [id: 0x15efb7d2, L:<*> - R:customers-service.spring-petclinic.svc.cluster.local<*>] The connection observed an error io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection timed out",1
1472626e,"2021-<*>-<*> <*>:<*>:<*>.<*> ERROR [api-gateway,5da664bffe85fe47,5da664bffe85fe47,true] <*> --- [or-http-epoll-<*>] a.w.r.e.AbstractErrorWebExceptionHandler : [c99c95db-<*>] <*> Server Error for HTTP POST ""/api/customer/owners"" io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection timed out Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: Error has been observed at the following site(s): |_ checkpoint ? org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain] |_ checkpoint ? org.springframework.cloud.sleuth.instrument.web.TraceWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain] |_ checkpoint ? HTTP POST ""/api/customer/owners"" [ExceptionHandlingWebHandler] Stack trace:",1
1f31ff81,"2021-<*>-<*> <*>:<*>:<*>.<*> ERROR <*> <*> --- [or-http-epoll-<*>] a.w.r.e.AbstractErrorWebExceptionHandler : <*> <*> Server Error for HTTP POST ""/api/customer/owners"" java.net.UnknownHostException: customers-service.spring-petclinic.svc.cluster.local at java.net.InetAddress.getAllByName0(InetAddress.java:<*>) Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: Error has been observed at the following site(s): |_ checkpoint ? org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain] |_ checkpoint ? org.springframework.cloud.sleuth.instrument.web.TraceWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain] |_ checkpoint ? HTTP POST ""/api/customer/owners"" [ExceptionHandlingWebHandler] Stack trace: at java.net.InetAddress.getAllByName0(InetAddress.java:<*>) at java.net.InetAddress.getAllByName(InetAddress.java:<*>) at java.net.InetAddress.getAllByName(InetAddress.java:<*>) at java.net.InetAddress.getByName(InetAddress.java:<*>) at io.netty.util.internal.SocketUtils$<*>.run(SocketUtils.java:<*>) at io.netty.util.internal.SocketUtils$<*>.run(SocketUtils.java:<*>) at java.security.AccessController.doPrivileged(Native Method) at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:<*>) at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:<*>) at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:<*>) at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:<*>) at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:<*>) at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:<*>) at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:<*>) at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:<*>) at io.netty.bootstrap.Bootstrap.access$<*>(Bootstrap.java:<*>) at io.netty.bootstrap.Bootstrap$<*>.operationComplete(Bootstrap.java:<*>) at io.netty.bootstrap.Bootstrap$<*>.operationComplete(Bootstrap.java:<*>) at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:<*>) at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:<*>) at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:<*>) at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:<*>) at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:<*>) at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:<*>) at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:<*>) at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:<*>) at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:<*>) at io.netty.channel.AbstractChannel$AbstractUnsafe.access$<*>(AbstractChannel.java:<*>) at io.netty.channel.AbstractChannel$AbstractUnsafe$<*>.run(AbstractChannel.java:<*>) at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:<*>) at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:<*>) at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:<*>) at io.netty.util.concurrent.SingleThreadEventExecutor$<*>.run(SingleThreadEventExecutor.java:<*>) at io.netty.util.internal.ThreadExecutorMap$<*>.run(ThreadExecutorMap.java:<*>) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:<*>) at java.lang.Thread.run(Thread.java:<*>)",2
ebf041ef,"2021-<*>-<*> <*>:<*>:<*>.<*> ERROR [api-gateway,1de75b761456b429,1de75b761456b429,true] <*> --- [or-http-epoll-<*>] a.w.r.e.AbstractErrorWebExceptionHandler : [d7ca4157-<*>] <*> Server Error for HTTP POST ""/api/customer/owners"" java.net.UnknownHostException: customers-service.spring-petclinic.svc.cluster.local: Temporary failure in name resolution at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: Error has been observed at the following site(s): |_ checkpoint ? org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain] |_ checkpoint ? org.springframework.cloud.sleuth.instrument.web.TraceWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain] |_ checkpoint ? HTTP POST ""/api/customer/owners"" [ExceptionHandlingWebHandler] Stack trace: at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) at java.net.InetAddress$<*>.lookupAllHostAddr(InetAddress.java:<*>) at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:<*>) at java.net.InetAddress.getAllByName0(InetAddress.java:<*>) at java.net.InetAddress.getAllByName(InetAddress.java:<*>) at java.net.InetAddress.getAllByName(InetAddress.java:<*>) at java.net.InetAddress.getByName(InetAddress.java:<*>) at io.netty.util.internal.SocketUtils$<*>.run(SocketUtils.java:<*>) at io.netty.util.internal.SocketUtils$<*>.run(SocketUtils.java:<*>) at java.security.AccessController.doPrivileged(Native Method) at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:<*>) at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:<*>) at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:<*>) at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:<*>) at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:<*>) at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:<*>) at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:<*>) at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:<*>) at io.netty.bootstrap.Bootstrap.access$<*>(Bootstrap.java:<*>) at io.netty.bootstrap.Bootstrap$<*>.operationComplete(Bootstrap.java:<*>) at io.netty.bootstrap.Bootstrap$<*>.operationComplete(Bootstrap.java:<*>) at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:<*>) at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:<*>) at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:<*>) at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:<*>) at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:<*>) at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:<*>) at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:<*>) at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:<*>) at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:<*>) at io.netty.channel.AbstractChannel$AbstractUnsafe.access$<*>(AbstractChannel.java:<*>) at io.netty.channel.AbstractChannel$AbstractUnsafe$<*>.run(AbstractChannel.java:<*>) at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:<*>) at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:<*>) at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:<*>) at io.netty.util.concurrent.SingleThreadEventExecutor$<*>.run(SingleThreadEventExecutor.java:<*>) at io.netty.util.internal.ThreadExecutorMap$<*>.run(ThreadExecutorMap.java:<*>) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:<*>) at java.lang.Thread.run(Thread.java:<*>)",1
d2bd26da,2021-<*>-<*> <*>:<*>:<*>.<*> WARN <*> <*> --- [<*>/...] i.f.k.c.d.i.WatchConnectionManager : Exec Failure java.net.SocketTimeoutException: sent ping but didn't receive pong within 30000ms (after <*> successful ping/pongs) at okhttp3.internal.ws.RealWebSocket.writePingFrame(RealWebSocket.java:<*>) at okhttp3.internal.ws.RealWebSocket$PingRunnable.run(RealWebSocket.java:<*>) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:<*>) at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:<*>) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$<*>(ScheduledThreadPoolExecutor.java:<*>) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:<*>) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:<*>) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:<*>) at java.lang.Thread.run(Thread.java:<*>),2
e095e712,2021-<*>-<*> <*>:<*>:<*>.<*> WARN <*> <*> --- [<*>/...] i.f.k.c.d.i.WatchConnectionManager : Exec Failure java.net.SocketTimeoutException: connect timed out at java.net.PlainSocketImpl.socketConnect(Native Method) at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:<*>) at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:<*>) at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:<*>) at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:<*>) at java.net.Socket.connect(Socket.java:<*>) at okhttp3.internal.platform.Platform.connectSocket(Platform.java:<*>) at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:<*>) at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:<*>) at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:<*>) at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:<*>) at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:<*>) at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:<*>) at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createHttpClient$<*>(HttpClientUtils.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:<*>) at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:<*>) at okhttp3.RealCall$AsyncCall.execute(RealCall.java:<*>) at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:<*>) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:<*>) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:<*>) at java.lang.Thread.run(Thread.java:<*>),3
49f363ad,"2021-<*>-<*> <*>:<*>:<*>.<*> ERROR <*> <*> --- [or-http-epoll-<*>] a.w.r.e.AbstractErrorWebExceptionHandler : <*> <*> Server Error for HTTP <*> ""/api/visit/owners/<*>/pets/<*>/visits"" io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: No route to host: visits-service.spring-petclinic.svc.cluster.local<*> Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: Error has been observed at the following site(s): |_ checkpoint ? org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain] |_ checkpoint ? org.springframework.cloud.sleuth.instrument.web.TraceWebFilter [DefaultWebFilterChain] |_ checkpoint ? org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain] |_ checkpoint ? HTTP <*> ""/api/visit/owners/<*>/pets/<*>/visits"" [ExceptionHandlingWebHandler] Stack trace: Caused by: java.net.ConnectException: finishConnect(..) failed: No route to host at io.netty.channel.unix.Errors.throwConnectException(Errors.java:<*>) at io.netty.channel.unix.Socket.finishConnect(Socket.java:<*>) at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:<*>) at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:<*>) at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:<*>) at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:<*>) at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:<*>) at io.netty.util.concurrent.SingleThreadEventExecutor$<*>.run(SingleThreadEventExecutor.java:<*>) at io.netty.util.internal.ThreadExecutorMap$<*>.run(ThreadExecutorMap.java:<*>) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:<*>) at java.lang.Thread.run(Thread.java:<*>)",2
